name = "web-message-board"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "./"

# Pages Functions configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "issue-board-db"
database_id = "58c85d18-4868-4580-ad22-7767fccfc729"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "issue-board-db"
database_id = "58c85d18-4868-4580-ad22-7767fccfc729"
